title: Collin Sinclair
description: > # this means to ignore newlines until "baseurl:"
  The personal website of one Collin Sinclair: astrophysics/computer science student, musician, and outdoor recreator.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "collinsinclair/com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Collin Sinclair # add your name
author-img: collin-sunglasses.png # add your photo
about-author: I love to play with computers. # add description
social-twitter: collinmsinclair
# social-facebook: # add your Facebook handle
social-github: collinsinclair # add your Github handle
social-linkedin: collinsinclair
social-email: collinsinclair88@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
